const path = {
  home: '/',
  user: '/user',
  profile: '/user/profile',
  changePassword: '/user/password',
  login: '/login',
  register: '/register',
  logout: '/logout',
  salary: '/salary',
  schedule: '/schedule',
  detail: '/detail/id/:id',
  courseDetail: '/detail/id/:id/index',
  studentList: '/detail/id/:id/studentlist',
  studyRoadmap: '/detail/id/:id/studyRoadmap',
  classAttendance: '/detail/id/:id/classAttendance',
  classList: '/edu-class',
  employeeList: '/employeeList',
  inChargeCourse: '/my-course',
  forgotPassword: '/forgot-password',
  validateCode: '/validate-code',
  setNewPassword: '/set-new-password',
  subsessions: '/detail/id/:id/subsessions',
}
export default path
